defaults:
  - dataset: dtu
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: costvolume
  - model/decoder: splatting_cuda
  - loss: [mse, lpips, cam]

wandb:
  project: SHARE-rebuttal
  entity: sgvr-3dgs
  name: placeholder
  mode: disabled
  id: null

mode: train
allow_loose_ckpt: false

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 1
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  warm_up_steps: 2000
  cosine_lr: true

checkpointing:
  load: null
  every_n_train_steps: 20000  # 5000
  save_top_k: -1
  pretrained_model: null

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 1
  render_from_pred: false

test:
  output_path: outputs/test
  compute_scores: false
  eval_time_skip_steps: 0
  save_image: true
  save_video: false
  save_depth: true

  # sugar regularization
  surface_level: 0.3
  n_vertices_in_mesh: 1_000_000
  bboxmin: null
  bboxmax: null
  center_bbox: true
  gpu: 0
  eval: true
  extract_mesh: false



seed: 111123

trainer:
  max_steps: -1
  val_check_interval: null
  gradient_clip_val: null
  num_sanity_val_steps: 2

output_dir: /mnt/nas4/youngju/rebuttal/dtu/wo_mean_var
