defaults:
  - view_sampler: bounded

name: re10k
roots: [/mnt/nas3/youngju/re10k/re10k]
make_baseline_1: true
augment: true

image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false


num_context_views: 3
baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: false
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1


n_views: 10
test_context_views: [23, 24, 33]
test_target_views: [35, 25]
single_view: true

padding_size: 0
shift_rays_half_pixel: forward