defaults:
  - view_sampler: bounded

name: tanksandtemples
root_dir: /home/youngju/ssd/datasets/Tanks/
scan_id: [Francis] #! change this


make_baseline_1: true
augment: true

n_views: 3
num_context_views: 3

test_context_views: [23, 24, 33]
test_target_views: [35, 25]
test_ref_view: []
use_test_ref_views_as_src: true
single_view: true
view_selection_type: random # best or random

use_mask: true

image_shape: [224, 224]
original_image_shape: [540,960]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

generic_near_far: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1

padding_size: 0
shift_rays_half_pixel: forward